[package]
name = "notify"
version = "0.1.0"
authors = ["Richard Artoul <richardartoul@gmail.com>"]

[dependencies]

ethabi = "5.0.1"
rustc-hex = "1.0"
reqwest = "0.8.4"
serde_derive = "1.0.27"
serde = "1.0.27"
serde_json = "1.0.9"
error-chain = "0.11.0"